### ISSUE TITLE
`test/system/tangible_thing_test.rb:40` is flaky

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#1244]
This test fails semi-regularly with an error like this:

```
TangibleThingTest
  test_create_a_new_tangible_thing_and_update_it_on_a_macbook_pro_15_inch FAIL (28.98s)
        expected to find text "Update Your Profile" in "Tell us about you\nYour First Name\nYour Last Name\nYour Team Name\nYour Time Zone\n(GMT-12:00) International Date Line West\n(GMT-11:00) American Samoa\n(GMT-11:00) Midway Island\n(GMT-10:00) Hawaii\n(GMT-09:00) Alaska\n(GMT-08:00) Pacific Time (US & Canada)\n(GMT-08:00) Tijuana\n(GMT-07:00) Arizona\n(GMT-07:00) Mazatlan\n(GMT-07:00) Mountain Time (US & Canada)\n(GMT-06:00) Central America\n(GMT-06:00) Central Time (US & Canada)\n(GMT-06:00) Chihuahua\n(GMT-06:00) Guadalajara\n(GMT-06:00) Mexico City\n(GMT-06:00) Monterrey\n(GMT-06:00) Saskatchewan\n(GMT-05:00) Bogota\n(GMT-05:00) Eastern Time (US & Canada)\n(GMT-05:00) Indiana (East)\n(GMT-05:00) Lima\n(GMT-05:00) Quito\n(GMT-04:00) Atlantic Time (Canada)\n(GMT-04:00) Caracas\n(GMT-04:00) Georgetown\n(GMT-04:00) La Paz\n(GMT-04:00) Puerto Rico\n(GMT-04:00) Santiago\n(GMT-03:30) Newfoundland\n(GMT-03:00) Brasilia\n(GMT-03:00) Buenos Aires\n(GMT-03:00) Montevideo\n(GMT-02:00) Greenland\n(GMT-02:00) Mid-Atlantic\n(GMT-01:00) Azores\n(GMT-01:00) Cape Verde Is.\n(GMT+00:00) Edinburgh\n(GMT+00:00) Lisbon\n(GMT+00:00) London\n(GMT+00:00) Monrovia\n(GMT+00:00) UTC\n(GMT+01:00) Amsterdam\n(GMT+01:00) Belgrade\n(GMT+01:00) Berlin\n(GMT+01:00) Bern\n(GMT+01:00) Bratislava\n(GMT+01:00) Brussels\n(GMT+01:00) Budapest\n(GMT+01:00) Casablanca\n(GMT+01:00) Copenhagen\n(GMT+01:00) Dublin\n(GMT+01:00) Ljubljana\n(GMT+01:00) Madrid\n(GMT+01:00) Paris\n(GMT+01:00) Prague\n(GMT+01:00) Rome\n(GMT+01:00) Sarajevo\n(GMT+01:00) Skopje\n(GMT+01:00) Stockholm\n(GMT+01:00) Vienna\n(GMT+01:00) Warsaw\n(GMT+01:00) West Central Africa\n(GMT+01:00) Zagreb\n(GMT+01:00) Zurich\n(GMT+02:00) Athens\n(GMT+02:00) Bucharest\n(GMT+02:00) Cairo\n(GMT+02:00) Harare\n(GMT+02:00) Helsinki\n(GMT+02:00) Jerusalem\n(GMT+02:00) Kaliningrad\n(GMT+02:00) Kyiv\n(GMT+02:00) Pretoria\n(GMT+02:00) Riga\n(GMT+02:00) Sofia\n(GMT+02:00) Tallinn\n(GMT+02:00) Vilnius\n(GMT+03:00) Baghdad\n(GMT+03:00) Istanbul\n(GMT+03:00) Kuwait\n(GMT+03:00) Minsk\n(GMT+03:00) Moscow\n(GMT+03:00) Nairobi\n(GMT+03:00) Riyadh\n(GMT+03:00) St. Petersburg\n(GMT+03:00) Volgograd\n(GMT+03:30) Tehran\n(GMT+04:00) Abu Dhabi\n(GMT+04:00) Baku\n(GMT+04:00) Muscat\n(GMT+04:00) Samara\n(GMT+04:00) Tbilisi\n(GMT+04:00) Yerevan\n(GMT+04:30) Kabul\n(GMT+05:00) Ekaterinburg\n(GMT+05:00) Islamabad\n(GMT+05:00) Karachi\n(GMT+05:00) Tashkent\n(GMT+05:30) Chennai\n(GMT+05:30) Kolkata\n(GMT+05:30) Mumbai\n(GMT+05:30) New Delhi\n(GMT+05:30) Sri Jayawardenepura\n(GMT+05:45) Kathmandu\n(GMT+06:00) Almaty\n(GMT+06:00) Astana\n(GMT+06:00) Dhaka\n(GMT+06:00) Urumqi\n(GMT+06:30) Rangoon\n(GMT+07:00) Bangkok\n(GMT+07:00) Hanoi\n(GMT+07:00) Jakarta\n(GMT+07:00) Krasnoyarsk\n(GMT+07:00) Novosibirsk\n(GMT+08:00) Beijing\n(GMT+08:00) Chongqing\n(GMT+08:00) Hong Kong\n(GMT+08:00) Irkutsk\n(GMT+08:00) Kuala Lumpur\n(GMT+08:00) Perth\n(GMT+08:00) Singapore\n(GMT+08:00) Taipei\n(GMT+08:00) Ulaanbaatar\n(GMT+09:00) Osaka\n(GMT+09:00) Sapporo\n(GMT+09:00) Seoul\n(GMT+09:00) Tokyo\n(GMT+09:00) Yakutsk\n(GMT+09:30) Adelaide\n(GMT+09:30) Darwin\n(GMT+10:00) Brisbane\n(GMT+10:00) Canberra\n(GMT+10:00) Guam\n(GMT+10:00) Hobart\n(GMT+10:00) Melbourne\n(GMT+10:00) Port Moresby\n(GMT+10:00) Sydney\n(GMT+10:00) Vladivostok\n(GMT+11:00) Magadan\n(GMT+11:00) New Caledonia\n(GMT+11:00) Solomon Is.\n(GMT+11:00) Srednekolymsk\n(GMT+12:00) Auckland\n(GMT+12:00) Fiji\n(GMT+12:00) Kamchatka\n(GMT+12:00) Marshall Is.\n(GMT+12:00) Wellington\n(GMT+12:45) Chatham Is.\n(GMT+13:00) Nuku'alofa\n(GMT+13:00) Samoa\n(GMT+13:00) Tokelau Is.\n(GMT+10:00) Brisbane\nLogout"
        test/system/tangible_thing_test.rb:40:in `block in <class:TangibleThingTest>'
        test/application_system_test_case.rb:135:in `instance_eval'
        test/application_system_test_case.rb:135:in `block (2 levels) in device_test'
```

And it will usually pass after re-running CI.

**Comment by gazayas** [comment]
I'm not sure if it's related, but I'm also seeing this chromedriver error show up every now and then:
`Selenium::WebDriver::Error::UnknownError: unknown error: unhandled inspector error: {"code":-32000,"message":"Node with given id does not belong to the document"}`

If I'm reading things right, it seems like we have to wait for things to be fixed on their end: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4440
