### ISSUE TITLE
Call to invalid method in bullet_train-super_scaffolding-1.7.5/lib/scaffolding/transformer.rb

### ISSUE THREAD

**Issue by swombat** [bullet-train-co/bullet_train#1482]
```bash
➜  bamboo git:(main) rails generate super_scaffold Clients::Information Client,Team label:text_field
Generating Clients::Information model with 'bin/rails generate model Clients::Information client:references label:string'

Writing './app/controllers/account/clients/information_controller.rb'.
Fixing Standard Ruby on './app/controllers/account/clients/information_controller.rb'.
Writing './app/views/account/clients/information/index.html.erb'.
Writing './app/views/account/clients/information/_index.html.erb'.
Writing './app/views/account/clients/information/_information.html.erb'.
Writing './app/views/account/clients/information/edit.html.erb'.
Writing './app/views/account/clients/information/show.html.erb'.
Writing './app/views/account/clients/information/_form.html.erb'.
Writing './app/views/account/clients/information/new.html.erb'.
Writing './app/views/account/clients/information/_breadcrumbs.html.erb'.
Writing './app/views/api/v1/clients/information/_information.json.jbuilder'.
Writing './app/views/api/v1/clients/information/index.json.jbuilder'.
Writing './app/views/api/v1/clients/information/show.json.jbuilder'.
Writing './config/locales/en/clients/information.en.yml'.
Writing './app/controllers/api/v1/clients/information_controller.rb'.
Fixing Standard Ruby on './app/controllers/api/v1/clients/information_controller.rb'.
Writing './test/controllers/api/v1/clients/information_controller_test.rb'.
Fixing Standard Ruby on './test/controllers/api/v1/clients/information_controller_test.rb'.
/Users/danieltenner/.rvm/gems/ruby-3.3.0/gems/bullet_train-super_scaffolding-1.7.5/lib/scaffolding/transformer.rb:1354:in `scaffold_crud': undefined method `underscore!' for an instance of String (NoMethodError)

          "rails generate model #{child} #{parent.underscore!}:references #{attributes.join(" ")}"
                                                 ^^^^^^^^^^^^
Did you mean?  underscore
	from /Users/danieltenner/.rvm/gems/ruby-3.3.0/gems/bullet_train-super_scaffolding-1.7.5/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb:95:in `run'
```

```ruby
          "rails generate model #{child} #{parent.underscore!}:references #{attributes.join(" ")}"
```

There is no `underscore!` method, this is meant to be `underscore`.

Appears to have been introduced in 1.7.4:

```bash
➜  gems grep -R "underscore\!" .

./bullet_train-super_scaffolding-1.7.5/lib/scaffolding/transformer.rb:          "rails generate model #{child} #{parent.underscore!}:references #{attributes.join(" ")}"
./bullet_train-super_scaffolding-1.7.4/lib/scaffolding/transformer.rb:          "rails generate model #{child} #{parent.underscore!}:references #{attributes.join(" ")}"
```

(I have 1.6 versions too and they don't show this)

## Easy fix:

Remove the offending `!`.

**Comment by swombat** [comment]
Also, worth noting that I only ended up triggering this code because I tried to create a namespaced model called "Information".

This appears to have resulted in a migration creating a table "clients_information" instead of "clients_informations", so it doesn't get found by:

```ruby
migration_file_name = `grep "create_table :#{class_names_transformer.table_name}.*do |t|$" db/migrate/*`.split(":").first
```

Which is why the error code is triggered at all.

Not entirely sure why `Information` is behaving weirdly as a model. If I change it to something else like `Section` or `Attachment` there is no error.

**Comment by jagthedrummer** [comment]
`Information` is acting differently than `Section` or `Attachment` because the word "information" pluralizes to "information" (with no "s") whereas the others pluralize by adding an "s". I don't know if there's some kind of underlying bug, but that's what explains the difference in behavior.
