### ISSUE TITLE
Crash in rails generate super_scaffold: active_support/inflector/methods.rb:290:in `constantize': uninitialized constant ApiToken (NameError)

### ISSUE THREAD

**Issue by ndbroadbent** [bullet-train-co/bullet_train#1489]
I ran the following command in a new Bullet Train app:

```
rails generate super_scaffold Service Team service_name:super_select enabled:boolean api_token_id:text_field api_token_secret:password_field
```

```
/Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.3/lib/active_support/inflector/methods.rb:290:in `constantize': uninitialized constant ApiToken (NameError)

      Object.const_get(camel_cased_word)
            ^^^^^^^^^^
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.3/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/scaffolding/script.rb:146:in `block in check_required_options_for_attributes'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/scaffolding/script.rb:91:in `each'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/scaffolding/script.rb:91:in `check_required_options_for_attributes'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb:62:in `run'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/scaffolding/script.rb:212:in `<main>'
	from <internal:/Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.14/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/bullet_train/super_scaffolding.rb:29:in `run'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/generators/super_scaffold/super_scaffold_generator.rb:32:in `generate'
```

It looks like an issue with the inflector rules for API vs Api. (I've done something similar in other Rails apps I've worked on in the past.)

**Comment by ndbroadbent** [comment]
Oh it also happens for `token_id`:

```
rails generate super_scaffold Service Team service_name:super_select enabled:boolean token_id:text_field token_secret:password_field
WARNING: Use strings for Figaro configuration. true was converted to "true".
/Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.3/lib/active_support/inflector/methods.rb:290:in `const_get': uninitialized constant Token (NameError)

      Object.const_get(camel_cased_word)
            ^^^^^^^^^^
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.3/lib/active_support/inflector/methods.rb:290:in `constantize'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.3/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/scaffolding/script.rb:146:in `block in check_required_options_for_attributes'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/scaffolding/script.rb:91:in `each'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/scaffolding/script.rb:91:in `check_required_options_for_attributes'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb:62:in `run'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/scaffolding/script.rb:212:in `<main>'
	from <internal:/Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.14/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/ndbroadbent/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bullet_train-super_scaffolding-1.7.8/lib/bullet_train/super_scaffolding.rb:29:in `run'
```

I think this is a duplicate of #1456

**Comment by jagthedrummer** [comment]
Yep, definitely a duplicate of #1456 (which will hopefully be fixed soon).
