### ISSUE TITLE
bin/super-scaffold oauth-provider fails on application created from this repository

### ISSUE THREAD

**Issue by whitemerry** [bullet-train-co/bullet_train#15]
Creating new oauth provider on application created from this repository template causes error related to missing stripe provider files. 

```
➜  application git:(main) ✗ bin/super-scaffold oauth-provider omniauth-google-oauth2 google_oauth2 Oauth::GoogleAccount [...] [...] --icon=ti-google
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - ./app/models/oauth/stripe_account.rb
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/scaffolding/oauth_providers.rb:83:in `initialize'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/scaffolding/oauth_providers.rb:83:in `open'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/scaffolding/oauth_providers.rb:83:in `oauth_scaffold_file'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb:107:in `block in run'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb:103:in `each'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb:103:in `run'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/scaffolding/script.rb:99:in `<main>'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/bullet_train/super_scaffolding.rb:25:in `run'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/tasks/bullet_train/super_scaffolding_tasks.rake:10:in `block (2 levels) in <main>'
Tasks: TOP => bullet_train:super_scaffolding
(See full trace by running task with --trace)
```

Quick research shows that it's hardcoded check:
https://github.com/bullet-train-co/bullet_train-super_scaffolding/blob/f303a15b3815ece82fc683b9a81607631ffcfb00/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb#L80

Trying to generate stripe provider fails due to collision caused by files (and integration) already existing inside `bullet_train-integrations-stripe@1.0.3`.
```
➜  application git:(main) ✗ bin/super-scaffold oauth-provider omniauth-stripe-connect stripe_connect Oauth::StripeAccount [...] [...] --icon=ti-money

🚨 Before doing the actual Super Scaffolding, you'll need to generate the models like so:

  rails g model Oauth::StripeAccount uid:string data:jsonb user:references
  rails g model Integrations::StripeInstallation team:references oauth_stripe_account:references name:string
  rails g model Webhooks::Incoming::Oauth::StripeAccountWebhook data:jsonb processed_at:datetime verified_at:datetime oauth_stripe_account:references

However, don't do the `rake db:migrate` until after you re-run Super Scaffolding, as it will need to update some settings in those migrations.

➜  application git:(main) ✗ rails g model Oauth::StripeAccount uid:string data:jsonb user:references
      invoke  active_record
The name 'Oauth::StripeAccount' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative or use --skip-collision-check or --force to skip this check and run this generator again.
➜  application git:(main) ✗ rails g model Integrations::StripeInstallation team:references oauth_stripe_account:references name:string
      invoke  active_record
The name 'Integrations::StripeInstallation' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative or use --skip-collision-check or --force to skip this check and run this generator again.
➜  application git:(main) ✗ rails g model Webhooks::Incoming::Oauth::StripeAccountWebhook data:jsonb processed_at:datetime verified_at:datetime oauth_stripe_account:references
      invoke  active_record
The name 'Webhooks::Incoming::Oauth::StripeAccountWebhook' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative or use --skip-collision-check or --force to skip this check and run this generator again.
```

I believe that `bullet_train-super_scaffolding` should check files located in `bullet_train-integrations-stripe` instead of project ones, and it should ignore these files if `bullet_train-integrations-stripe` is not present in project (or is it required dependency?).

**Comment by whitemerry** [comment]
After commenting out all files form [oauth_provider_scaffolder.rb#L80](https://github.com/bullet-train-co/bullet_train-super_scaffolding/blob/f303a15b3815ece82fc683b9a81607631ffcfb00/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb#L80) it fails on another missing file:
```
➜  application git:(playground) ✗ bin/super-scaffold oauth-provider omniauth-google-oauth2 google_oauth2 Oauth::GoogleAccount [...] [...] --icon=ti-google
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - ./app/views/devise/shared/_oauth.html.erb
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/scaffolding/oauth_providers.rb:17:in `read'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/scaffolding/oauth_providers.rb:17:in `legacy_add_line_to_file'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/scaffolding/oauth_providers.rb:160:in `oauth_scaffold_add_line_to_file'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb:111:in `run'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/scaffolding/script.rb:99:in `<main>'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/bullet_train/super_scaffolding.rb:25:in `run'
/home/[...]/.rvm/gems/ruby-3.1.1/gems/bullet_train-super_scaffolding-1.0.21/lib/tasks/bullet_train/super_scaffolding_tasks.rake:10:in `block (2 levels) in <main>'
Tasks: TOP => bullet_train:super_scaffolding
(See full trace by running task with --trace)
```

And it's caused by `_oauth.html.erb` file location - `super-scaffolding` looks in project files and this partial has been moved to: https://github.com/bullet-train-co/bullet_train-base/blob/main/app/views/devise/shared/_oauth.html.erb

**Comment by andrewculver** [comment]
@whitemerry Should be fixed in https://github.com/bullet-train-co/bullet_train/pull/61 . This fix requires more than just bumping Ruby gem versions. You'll have to merge `main` from this repo into your application as well. See https://bullettrain.co/docs/upgrades for details.
