### ISSUE TITLE
undefined method 'owning_association'

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#1506]
I did this:

```
rails g super_scaffold Category Team name:text_field owning_team_id:super_select{class_name=Team}
```

And then when I ran `rails db:migrate` I got this error:

```
$ rails db:migrate
bin/rails aborted!
NoMethodError: undefined method 'owning_association' in 'category' factory (NoMethodError)
Did you mean? 'owning_association { :team }'


        raise NoMethodError.new(<<~MSG)
        ^^^^^
/Users/jgreen/projects/moonswitch/nfl-testbed/test/factories/categories.rb:5:in `block (2 levels) in <main>'
/Users/jgreen/projects/moonswitch/nfl-testbed/test/factories/categories.rb:2:in `block in <main>'
/Users/jgreen/projects/moonswitch/nfl-testbed/test/factories/categories.rb:1:in `<main>'
/Users/jgreen/projects/moonswitch/nfl-testbed/config/environment.rb:5:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

The error points to the factory, which looks like this:

```ruby
FactoryBot.define do
  factory :category do
    association :team
    name { "MyString" }
    owning_association :team
  end
end
```

`owning_association` isn't a method. I _think_ instead that line should be:

```
association :owning_team
```

**Comment by jagthedrummer** [comment]
Just trying to figure out how/where this problem occurs so I'm documenting the trail here.

I run this:

```
rails g super_scaffold Category Team name:text_field owning_team_id:super_select{class_name=Team}
```

And the first thing that happens is we run this command to generate the model:

```
bin/rails generate model Category team:references name:string owning_team:references
```

As part of that rails generates a factory, and at that point the factory looks like this:

```ruby
FactoryBot.define do
  factory :category do
    team { nil }
    name { "MyString" }
    owning_team { nil }
  end
end
```

Then eventually these lines are responsible for making the incorrect changes:
https://github.com/bullet-train-co/bullet_train-core/blob/9b7f280d3a981b11f8f925e946ebff4c1d029436/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L1363-L1370

The `scaffold_replace_line_in_file` method call ends up replacing `team { nil }` with `association: team`. For the primary `team` relationship that works OK, but for `owning_team` it's overeager in matching just part of that line and so `owning_team { nil }` gets turned into `owning_association :team`. This is incorrect in two different ways:

1. `owning_association` isn't a valid factory method
2. The association shouldn't be to just `:team`

It looks like this bug is unique to any `*_team` association that you might try to scaffold. It doesn't happen if you included an `owning_user` association, for instance.

With an `owning_user` association:

```
rails g super_scaffold Category Team name:text_field owning_user_id:super_select{class_name=User}
```

Rails generates this factory:

```ruby
FactoryBot.define do
  factory :category do
    team { nil }
    name { "MyString" }
    owning_user { nil }
  end
end
```

which ends up like this after the transformer does its thing:

```ruby
FactoryBot.define do
  factory :category do
    association :team
    name { "MyString" }
    owning_user { nil }
  end
end
```

Maybe we nee to include line beginning and ending terminators in that bit of the transformer to ensure that we're _only_ munging the primary `team` relationship.
