### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by EdgeCaseLord** [bullet-train-co/bullet_train#1550]
Hi there, I'm just trying BulletTrain for the first time, and running the config script, Yarn complains about unmet dependenciesand some other problems. I don't know whether that's dramatic, but maybe update the prject's dependencies?
Here's the Yarn output:
```
  yarn install v1.22.19
warning ../../package.json: No license field
  [1/4] Resolving packages...
warning @redocly/cli > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @redocly/cli > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning yalc > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning yalc > npm-packlist > glob@7.2.3: Glob versions prior to v9 are no longer supported
  [2/4] Fetching packages...
  [3/4] Linking dependencies...
warning " > @rails/actiontext@7.1.3" has unmet peer dependency "trix@^2.0.0".
warning "@redocly/cli > redoc > @cfaester/enzyme-adapter-react-18@0.8.0" has unmet peer dependency "enzyme@^3.11.0".
warning " > stimulus-scroll-reveal@3.2.0" has unmet peer dependency "@hotwired/stimulus@^3.2.1".
  [4/4] Building fresh packages...
  success Saved lockfile.
  Done in 57.14s.
  ```
  Steps to reproduce: Follow set up instructions in readme and config script

**Comment by badde-media** [comment]
Reopening this issue because there's a whole bunch of unmet dependencies as it looks like. Ok those I've mentioned are second- or thhird level deps, which I could solve by installing them manually using Yarn add. But in the next step, the installer fails to set up the database. This should be added to the configuration or setup scripts, but has nothing to do with the missing dependencies. 

After adding the missing js dependencies and manually setting up the database and rails credentials for it, instead of starting the server and giving me a smooth development experience, bin/dev exits telling me this:
```
worker           | You are connecting to Redis 6.0.16, Sidekiq requires Redis 6.2.0 or greater
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-7.2.4/lib/sidekiq/cli.rb:77:in `run'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-7.2.4/bin/sidekiq:31:in `<top (required)>'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/bin/sidekiq:25:in `load'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/bin/sidekiq:25:in `<top (required)>'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/bin/bundle:25:in `load'
worker           | /home/jin/.asdf/installs/ruby/3.3.2/bin/bundle:25:in `<main>'
worker           | Exited with code 1
light-css        |
light-css        | Rebuilding...
web              | Interrupting...
js               | Interrupting...
light-css        | Interrupting...
light-mailer-css | Interrupting...
web              | [212287] - Gracefully shutting down workers...
js               | Exited with code 0
light-mailer-css | Exited with code 0
light-css        | Exited with code 0
web              | [212287] === puma shutdown: 2024-06-19 22:13:29 +0300 ===
web              | [212287] - Goodbye!
web              | Exiting
web              | Exited with code 0
```
Unfortunately, there is no Redis 6.2.0 gem in the gems repository. Not even after running gem update --system. The most recent version from just a little while ago is gem 'redis', '~> 5.2'. Possibly a typo?

**Comment by badde-media** [comment]
Oh I see, that's a Sidekiq issue, also not yours

**Comment by badde-media** [comment]
Unfortunately, even if this issue isn't your fault, it hinders me from using your app. I have to switch to RailsUI or so, which offers much less features, but at least boots up without any issues.

**Comment by badde-media** [comment]
I've fixed the error in Sidekick that prevented the booting of BulletTrain. The app boots now. Unfortunately, my pull request was disregarded by the Sidekiq maintainer. 

But there's still a whole bunch of errors piling up in the log like 
```
worker           | 2024-06-19T19:34:42.656Z pid=231024 tid=4ezo ERROR: ERR Error running script (call to f_000a4c2f82df69db1780053377a2c9b0741570e0): @user_script:2: ERR value is not an integer or out of range (redis://localhost:6379)
```
about one per second. And seriously, the app is not quite intuitive to use, even not after reading the docs about super-scaffolding and creative concepts. Not going to use it for now.
