### ISSUE TITLE
Chromedriver issue?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#235]
```
E

Error:
TeamsTest#test_admin_can't_create_empty_team_on_a_macbook_pro_15_inch:
Selenium::WebDriver::Error::WebDriverError: Unable to find chromedriver. Please download the server from
https://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH.
More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.

    test/application_system_test_case.rb:102:in `resize_for'
    test/system/teams_test.rb:29:in `block (2 levels) in <class:TeamsTest>'

Error:
TeamsTest#test_admin_can't_create_empty_team_on_a_macbook_pro_15_inch:
Selenium::WebDriver::Error::WebDriverError: Unable to find chromedriver. Please download the server from
https://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH.
More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.

    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/service.rb:104:in `binary_path'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/service.rb:73:in `initialize'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/service.rb:32:in `new'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/service.rb:32:in `chrome'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/driver.rb:370:in `service_url'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/driver.rb:311:in `create_bridge'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/driver.rb:47:in `new'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/common/driver.rb:47:in `for'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver.rb:89:in `for'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/capybara-a930528c92a6/lib/capybara/selenium/driver.rb:83:in `browser'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/capybara-a930528c92a6/lib/capybara/selenium/driver.rb:161:in `save_screenshot'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/capybara-a930528c92a6/lib/capybara/session.rb:748:in `block in save_screenshot'
    <internal:kernel>:90:in `tap'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/capybara-a930528c92a6/lib/capybara/session.rb:748:in `save_screenshot'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:99:in `save_image'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:36:in `take_screenshot'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:45:in `take_failed_screenshot'
    /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:8:in `before_teardown'


rails test test/system/teams_test.rb:28
```

**Comment by andrewculver** [comment]
Not sure what this was. It went away.
