### ISSUE TITLE
Rails couldn't find a valid model

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/bullet_train#270]
I created several teams in console, and then when I try to destroy them all with `Team.destroy_all`, I get this error:

```
3.1.2 :008 > Team.destroy_all
  Team Load (8.8ms)  SELECT "teams".* FROM "teams"
  TRANSACTION (0.3ms)  BEGIN
  Team Update (9.9ms)  UPDATE "teams" SET "being_destroyed" = $1 WHERE "teams"."id" = $2  [["being_destroyed", true], ["id", 1]]
  Webhooks::Outgoing::Event Load (7.7ms)  SELECT "webhooks_outgoing_events".* FROM "webhooks_outgoing_events" WHERE "webhooks_outgoing_events"."team_id" = $1  [["team_id", 1]]
  Scaffolding::AbsolutelyAbstract::CreativeConcept Load (6.3ms)  SELECT "scaffolding_absolutely_abstract_creative_concepts".* FROM "scaffolding_absolutely_abstract_creative_concepts" WHERE "scaffolding_absolutely_abstract_creative_concepts"."team_id" = $1  [["team_id", 1]]
  Membership Load (1.4ms)  SELECT "memberships".* FROM "memberships" WHERE "memberships"."team_id" = $1  [["team_id", 1]]
  Webhooks::Outgoing::Event Update All (0.5ms)  UPDATE "webhooks_outgoing_events" SET "subject_id" = $1, "subject_type" = $2 WHERE "webhooks_outgoing_events"."subject_id" = $3 AND "webhooks_outgoing_events"."subject_type" = $4  [["subject_id", nil], ["subject_type", nil], ["subject_id", 1], ["subject_type", "Membership"]]
  Scaffolding::CompletelyConcrete::TangibleThings::Assignment Load (2.8ms)  SELECT "scaffolding_completely_concrete_tangible_things_assignments".* FROM "scaffolding_completely_concrete_tangible_things_assignments" WHERE "scaffolding_completely_concrete_tangible_things_assignments"."membership_id" = $1  [["membership_id", 1]]
  TRANSACTION (0.1ms)  ROLLBACK
/Users/yurisidorov/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.3/lib/active_record/reflection.rb:441:in `rescue in compute_class': Rails couldn't find a valid model for Memberships::Reassignments::ScaffoldingCompletelyConcreteTangibleThingsReassignment association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass. (NameError)

          raise NameError, msg
          ^^^^^
/Users/yurisidorov/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.3/lib/active_record/inheritance.rb:259:in `compute_type': uninitialized constant Membership::Memberships::Reassignments::ScaffoldingCompletelyConcreteTangibleThingsReassignment (NameError)

            raise NameError.new("uninitialized constant #{candidates.first}", candidates.first)
            ^^^^^
```

**Comment by gazayas** [comment]
@newstler `Team.destroy_all` should work now that [bullet_train-base#67](https://github.com/bullet-train-co/bullet_train-base/pull/67) was merged in

**Comment by jagthedrummer** [comment]
Fixed in https://github.com/bullet-train-co/bullet_train-base/pull/67
