### ISSUE TITLE
Sidekiq outputting tedious logs

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train#380]
After the new merges I'm getting these logs

```
worker           | Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
worker           |   redis.brpop("queue:critical", "queue:default", "queue:mailers", "queue:low", "queue:action_mailbox_routing", timeout: 2)(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
worker           | Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
worker           |   redis.brpop("queue:critical", "queue:default", "queue:mailers", "queue:low", "queue:action_mailbox_routing", timeout: 2)(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
worker           | Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
worker           |   redis.brpop("queue:critical", "queue:default", "queue:mailers", "queue:low", "queue:action_mailbox_routing", timeout: 2)(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
worker           | Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
worker           |   redis.brpop("queue:critical", "queue:default", "queue:mailers", "queue:low", "queue:action_mailbox_routing", timeout: 2)(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
worker           | Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
worker           |   redis.brpop("queue:critical", "queue:default", "queue:mailers", "queue:low", "queue:action_mailbox_routing", timeout: 2)(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
worker           | Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
worker           |   redis.brpop("queue:critical", "queue:default", "queue:mailers", "queue:low", "queue:action_mailbox_routing", timeout: 2)(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
worker           | Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
worker           |   redis.brpop("queue:critical", "queue:default", "queue:mailers", "queue:low", "queue:action_mailbox_routing", timeout: 2)(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
worker           | Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:
worker           |   redis.brpop("queue:critical", "queue:default", "queue:mailers", "queue:low", "queue:action_mailbox_routing", timeout: 2)(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
worker           | Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /home/gazayas/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/launcher.rb:168:in `block (2 levels) in ❤')

```

At least there's a heart at the end? :heart:

**Comment by gazayas** [comment]
Already fixed on main according to an issue opened over at sidekiq yesterday. We just need to wait until the next version is released :+1:

**Comment by gazayas** [comment]
Fixed since merging in https://github.com/bullet-train-co/bullet_train/pull/391 which includes the update to Sidekiq 6.5.6.
Here's the main issue: https://github.com/mperham/sidekiq/issues/5488
