### ISSUE TITLE
bundle exec rake assets:precompiled failed

### ISSUE THREAD

**Issue by vsnguyen** [bullet-train-co/bullet_train#622]
From Render Logs:

```
yarn run v1.22.19
Jan 19 11:14:00 AM  $ node esbuild.config.js
Jan 19 11:14:00 AM  ✘ [ERROR] Could not resolve ""
Jan 19 11:14:00 AM  
Jan 19 11:14:00 AM  resolveDir /opt/render/project/src/app/javascript/controllers
Jan 19 11:14:00 AM  path ./**/*_controller.js
Jan 19 11:14:01 AM  error Command failed with exit code 1.
Jan 19 11:14:01 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Jan 19 11:14:01 AM  rake aborted!
Jan 19 11:14:01 AM  jsbundling-rails: Command build failed, ensure yarn is installed and `yarn build` runs without errors
Jan 19 11:14:01 AM  E, [2023-01-19T16:14:01.026399 #112] ERROR -- honeybadger: ** [Honeybadger] Unable to send error report: API key is missing. id=eb2c0200-122c-408a-9fcf-6cb789d3df74 level=3 pid=112
Jan 19 11:14:01 AM  /opt/render/project/.gems/ruby/3.2.0/gems/jsbundling-rails-1.1.1/lib/tasks/jsbundling/build.rake:5:in `block (2 levels) in <main>'
Jan 19 11:14:01 AM  /opt/render/project/.gems/ruby/3.2.0/gems/sentry-ruby-5.7.0/lib/sentry/rake.rb:26:in `execute'
Jan 19 11:14:01 AM  /opt/render/project/.gems/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Jan 19 11:14:01 AM  /opt/render/project/.gems/bin/bundle:108:in `load'
Jan 19 11:14:01 AM  /opt/render/project/.gems/bin/bundle:108:in `<main>'
Jan 19 11:14:01 AM  Tasks: TOP => assets:precompile => javascript:build
Jan 19 11:14:01 AM  (See full trace by running task with --trace)
Jan 19 11:14:01 AM  ==> Build failed 😞
```

From Docker:
```
root@7c5d951a629f:/app# bundle exec rake assets:precompile --trace
WARNING: Use strings for Figaro configuration. false was converted to "false".
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke javascript:build (first_time)
** Execute javascript:build
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.21s.
yarn run v1.22.19
$ node esbuild.config.js
✘ [ERROR] Could not resolve ""

resolveDir /app/app/javascript/controllers
path ./**/*_controller.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rake aborted!
jsbundling-rails: Command build failed, ensure yarn is installed and `yarn build` runs without errors
/usr/local/bundle/gems/jsbundling-rails-1.1.1/lib/tasks/jsbundling/build.rake:5:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:25:in `load'
/usr/local/bin/rake:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => assets:precompile => javascript:build
```

**Comment by vsnguyen** [comment]
@gazayas 

The problem lies within the `bundle exec rake assets:precompile` command which triggers `node esbuild.config.js` which produces the error `[ERROR] Could not resolve ""`.

I've deployed about 5 times with the same error.

**Comment by gazayas** [comment]
@vsnguyen Thanks for opening your PR at #627. For what it's worth, I just deployed an app to Render with our one-click button from the readme, and all I had to do was set the `BASE_URL` manually to get it working, so I'm not entirely sure where this is coming from. I haven't done this with Docker yet though, so maybe I'm overlooking a configuration setting there.

**Comment by vsnguyen** [comment]
@gazayas 

Basically, when the env THEME isn't set, the variable themeFile is defaulted to an empty string.  themeFile is then used downstream on esbuild entrypoints which blows up because themeFile is an empty string.

**Comment by jagthedrummer** [comment]
Fixed in https://github.com/bullet-train-co/bullet_train/pull/627
