### ISSUE TITLE
System tests fail after running Super Scaffolding test setup

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train#651]
I'm assuming this is low-priority because we only run the test setup script to check the Super Scaffolding system test:

```
> bundle exec test/bin/setup-super-scaffolding-system-test
> rails test test/system/super_scaffolding_test.rb
```
However, we get a failure and an error when running all the system tests.
<details>
  <summary>Failing Tests</summary>

```
E

Error:
ApplicationPlatformSystemTest#test_visitors_can_sign-up_and_manage_team_members_with_subscriptions_disabled_on_a_macbook_pro_15_inch:
Capybara::ElementNotFound: Unable to find visible link or button "Team Members"
    test/system/application_platform_test.rb:68:in `block (3 levels) in <class:ApplicationPlatformSystemTest>'
    test/application_system_test_case.rb:108:in `within_team_menu_for'
    test/system/application_platform_test.rb:67:in `block (2 levels) in <class:ApplicationPlatformSystemTest>'


rails test test/system/application_platform_test.rb:18


F

Failure:
SuperScaffoldingSystemTest#test_developers_can_Super_Scaffold_a_file_partial_and_perfrom_crud_actions_on_the_record [/home/gazayas/work/bt/bullet_train/test/system/super_scaffolding_partial_test.rb:50]:
Expected false to be truthy.


rails test test/system/super_scaffolding_partial_test.rb:36
```
</details>

If we can get these tests to pass, it can prevent developers from getting confused in case they run `bundle exec rails test:system` instead of just the Super Scaffolding system test.

**Comment by gazayas** [comment]
I see, this is why it's not finding "Team Members" in the Team Menu in the navbar.

![image](https://user-images.githubusercontent.com/10546292/218667852-2c377a26-176c-4e6a-9694-14e3e3aa15d0.png)

Maybe we should just visit the page instead of click to it? There are other places where we click "Team Members" so I think this should be okay.

**Comment by gazayas** [comment]
I also have a feeling the Super Scaffolding partials test failure was addressed a while ago before `bullet_train-core`, I'll have to look for it.

**Comment by gazayas** [comment]
Linking https://github.com/bullet-train-co/bullet_train/pull/343
