### ISSUE TITLE
Problems with passing a local path to `bin/hack`

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#928]
```
$ bin/hack --link ../bullet_train-core/
bullet_train is directly present in the `Gemfile`, so we'll update that line.
bullet_train-api is directly present in the `Gemfile`, so we'll update that line.
Could not find bullet_train-fields. Adding to the end of the Gemfile.
Could not find bullet_train-has_uuid. Adding to the end of the Gemfile.
bullet_train-incoming_webhooks is directly present in the `Gemfile`, so we'll update that line.
bullet_train-integrations is directly present in the `Gemfile`, so we'll update that line.
bullet_train-integrations-stripe is directly present in the `Gemfile`, so we'll update that line.
bullet_train-obfuscates_id is directly present in the `Gemfile`, so we'll update that line.
bullet_train-outgoing_webhooks is directly present in the `Gemfile`, so we'll update that line.
bullet_train-scope_questions is directly present in the `Gemfile`, so we'll update that line.
Could not find bullet_train-scope_validator. Adding to the end of the Gemfile.
bullet_train-sortable is directly present in the `Gemfile`, so we'll update that line.
bullet_train-super_scaffolding is directly present in the `Gemfile`, so we'll update that line.
Could not find bullet_train-super_load_and_authorize_resource. Adding to the end of the Gemfile.
bullet_train-themes is directly present in the `Gemfile`, so we'll update that line.
bullet_train-themes-light is directly present in the `Gemfile`, so we'll update that line.
Could not find bullet_train-themes-tailwind_css. Adding to the end of the Gemfile.

/Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:106:in `parse':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: Illformed requirement ["../bullet_train-core/"]. Bundler cannot continue.

 #  from /Users/jgreen/projects/bullet-train-co/bullet_train/Gemfile:100
 #  -------------------------------------------
 #  # Core packages.
 >  gem "bullet_train", "../bullet_train-core/"
 #  gem "bullet_train-super_scaffolding", "../bullet_train-core/"
 #  -------------------------------------------

        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:138:in `block in initialize'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:138:in `map!'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:138:in `initialize'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:63:in `new'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:63:in `create'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/dependency.rb:56:in `initialize'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dependency.rb:31:in `initialize'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:101:in `new'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:101:in `gem'
        from /Users/jgreen/projects/bullet-train-co/bullet_train/Gemfile:100:in `eval_gemfile'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:49:in `instance_eval'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:49:in `eval_gemfile'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:12:in `evaluate'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/definition.rb:37:in `build'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler.rb:217:in `definition'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler.rb:165:in `setup'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/setup.rb:23:in `block in <top (required)>'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/ui/shell.rb:159:in `with_level'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/ui/shell.rb:111:in `silence'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/setup.rb:23:in `<top (required)>'
        from <internal:/Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems.rb:1370:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
/Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:106:in `parse': Illformed requirement ["../bullet_train-core/"] (Gem::Requirement::BadRequirementError)
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:138:in `block in initialize'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:138:in `map!'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:138:in `initialize'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:63:in `new'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/requirement.rb:63:in `create'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/dependency.rb:56:in `initialize'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dependency.rb:31:in `initialize'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:101:in `new'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:101:in `gem'
        from /Users/jgreen/projects/bullet-train-co/bullet_train/Gemfile:100:in `eval_gemfile'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:49:in `instance_eval'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:49:in `eval_gemfile'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:12:in `evaluate'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/definition.rb:37:in `build'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler.rb:217:in `definition'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler.rb:165:in `setup'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/setup.rb:23:in `block in <top (required)>'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/ui/shell.rb:159:in `with_level'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/ui/shell.rb:111:in `silence'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/bundler/setup.rb:23:in `<top (required)>'
        from <internal:/Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/jgreen/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems.rb:1370:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
```

It does modify the `Gemfile`, but not in the correct way. All of the BT lines look like this:

```
gem "bullet_train", "../bullet_train-core/"
gem "bullet_train-super_scaffolding", "../bullet_train-core/"
```

But they should look like this:

```
gem "bullet_train", "../bullet_train-core/bullet_train"
gem "bullet_train-super_scaffolding", "../bullet_train-core/bullet_train-super_scaffolding"
```

**Comment by gazayas** [comment]
Interesting, it's working fine for me against `main`, so I'll have to dig and see where the bug is.

<details>
  <summary>bin/hack --link ../bullet_train-core/</summary>

```
> git log -1
commit 556030da0b39e8721acd338e0b04da2d1a71221a (HEAD -> testing, origin/main, origin/HEAD, main)
Author: Jeremy Green <jagthedrummer@gmail.com>
Date:   Mon Aug 28 14:02:10 2023 -0700

    Show BulletTrain gems in stack traces by default (#933)
    
    * Show BulletTrain gems in stack traces by default
    
    Fixes https://github.com/bullet-train-co/bullet_train/issues/681
    
    * heckin linter
> bin/hack --link ../bullet_train-core/
bullet_train is directly present in the `Gemfile`, so we'll update that line.
bullet_train-api is directly present in the `Gemfile`, so we'll update that line.
Could not find bullet_train-fields. Adding to the end of the Gemfile.
Could not find bullet_train-has_uuid. Adding to the end of the Gemfile.
bullet_train-incoming_webhooks is directly present in the `Gemfile`, so we'll update that line.
bullet_train-integrations is directly present in the `Gemfile`, so we'll update that line.
bullet_train-integrations-stripe is directly present in the `Gemfile`, so we'll update that line.
bullet_train-obfuscates_id is directly present in the `Gemfile`, so we'll update that line.
bullet_train-outgoing_webhooks is directly present in the `Gemfile`, so we'll update that line.
bullet_train-scope_questions is directly present in the `Gemfile`, so we'll update that line.
Could not find bullet_train-scope_validator. Adding to the end of the Gemfile.
bullet_train-sortable is directly present in the `Gemfile`, so we'll update that line.
bullet_train-super_scaffolding is directly present in the `Gemfile`, so we'll update that line.
Could not find bullet_train-super_load_and_authorize_resource. Adding to the end of the Gemfile.
bullet_train-themes is directly present in the `Gemfile`, so we'll update that line.
bullet_train-themes-light is directly present in the `Gemfile`, so we'll update that line.
Could not find bullet_train-themes-tailwind_css. Adding to the end of the Gemfile.

  Fetching gem metadata from https://rubygems.org/.......
  Using rake 13.0.6
  Using minitest 5.19.0
  Using builder 3.2.4
  Using erubi 1.12.0
  Using racc 1.7.1
  Using concurrent-ruby 1.2.2
  Using crass 1.0.6
  Using nio4r 2.5.9
  Using websocket-extensions 0.1.5
  Using marcel 1.0.2
  Using mini_mime 1.1.5
  Using rack 2.2.8
  Using date 3.3.3
  Using timeout 0.4.0
  Using ast 2.4.2
  Using public_suffix 5.0.3
  Using aws-partitions 1.812.0
  Using jmespath 1.6.2
  Using aws_cf_signer 0.1.3
  Using base64 0.1.1
  Using awesome_print 1.9.2
  Using bindex 0.8.1
  Using debug_inspector 1.1.0
  Using aws-eventstream 1.2.0
  Using bcrypt 3.1.19
  Using msgpack 1.7.2
  Using chronic 0.10.2
  Using http-accept 1.7.0
  Using unf_ext 0.0.8.2
  Using mime-types-data 3.2023.0808
  Using netrc 0.11.0
  Using bundler 2.4.10
  Using thor 1.2.2
  Using zeitwerk 2.6.11
  Using cancancan 3.5.0
  Using bullet_train-scope_validator 1.3.18 from source at `local/bullet_train-core/bullet_train-scope_validator`
  Using phonelib 0.8.3
  Using method_source 1.0.0
  Using thread-local 1.1.0
  Using orm_adapter 0.5.0
  Using commonmarker 0.23.10
  Using pwned 2.0.2
  Using email_reply_parser 0.5.11
  Using fastimage 2.2.7
  Using hiredis 0.6.3
  Using charlock_holmes 0.7.7
  Using http_accept_language 2.1.1
  Using mini_magick 4.12.0
  Using ffi 1.15.5
  Using possessive 1.0.1
  Using pagy 6.0.4
  Using htmlentities 4.3.4
  Using faraday-net_http 3.0.2
  Using ruby2_keywords 0.0.5
  Using multipart-post 2.3.0
  Using connection_pool 2.4.1
  Using unicode-version 1.3.0
  Using xxhash 0.5.0
  Using hashie 5.0.0
  Using jwt 2.7.1
  Using multi_xml 0.6.0
  Using hashids 1.0.6
  Using version_gem 1.1.3
  Using matrix 0.4.2
  Using stripe 9.0.0
  Using regexp_parser 2.8.1
  Using chunky_png 1.4.0
  Using sexp_processor 4.17.0
  Using coderay 1.1.3
  Using colorize 1.1.0
  Using io-console 0.6.0
  Using rotp 6.2.2
  Using docile 1.4.0
  Using erubis 2.7.0
  Using honeybadger 5.2.1
  Using foreman 0.87.2
  Using json 2.6.3
  Using knapsack_pro 5.6.0
  Using language_server-protocol 3.17.0.3
  Using lint_roller 1.1.0
  Using rails_autoscale_agent 0.12.0
  Using require_all 3.0.0
  Using ruby-progressbar 1.13.0
  Using rainbow 3.1.1
  Using parallel 1.23.0
  Using pg 1.5.3
  Using rexml 3.2.6
  Using rqrcode_core 1.2.0
  Using websocket 1.2.9
  Using simplecov-html 0.12.3
  Using unicode-display_width 2.4.2
  Using rubyzip 2.3.2
  Using simplecov_json_formatter 0.1.4
  Using minitest-retry 0.2.2
  Using websocket-driver 0.7.6
  Using nokogiri 1.15.4 (x86_64-linux)
  Using puma 6.3.1
  Using tzinfo 2.0.6
  Using net-protocol 0.2.1
  Using parser 3.2.2.3
  Using i18n 1.14.1
  Using rack-test 2.1.0
  Using addressable 2.8.5
  Using binding_of_caller 1.0.0
  Using sentry-ruby 5.10.0
  Using rack-cors 2.0.1
  Using warden 1.2.9
  Using sprockets 4.2.0
  Using aws-sigv4 1.6.0
  Using mime-types 3.5.1
  Using unf 0.1.4
  Using figaro 1.2.0
  Using ruby-vips 2.1.4
  Using faraday 2.7.10
  Using faraday-multipart 1.0.4
  Using rack-mini-profiler 3.1.1
  Using bootsnap 1.16.0
  Using redis-client 0.16.0
  Using unicode-emoji 3.3.2
  Using omniauth 1.9.2
  Using snaky_hash 2.0.1
  Using code_analyzer 0.5.5
  Using pry 0.14.2
  Using reline 0.3.8
  Using postmark 1.24.0
  Using selenium-webdriver 4.11.0
  Using simplecov 0.22.0
  Using rqrcode 2.2.0
  Using net-pop 0.1.2
  Using net-smtp 0.3.3
  Using activesupport 7.0.7.2
  Using css_parser 1.14.0
  Using launchy 2.5.2
  Using net-imap 0.3.7
  Using rubocop-ast 1.29.0
  Using aws-sdk-core 3.181.0
  Using domain_name 0.5.20190701
  Using loofah 2.21.3
  Using image_processing 1.12.2
  Using xpath 3.2.0
  Using ruby-openai 5.1.0
  Using simpleidn 0.2.1
  Using sidekiq 7.1.2
  Using pry-stack_explorer 0.6.1
  Using redis 5.0.7
  Using irb 1.7.4
  Using rails-dom-testing 2.2.0
  Using globalid 1.1.0
  Using mail 2.8.1
  Using activemodel 7.0.7.2
  Using active_hash 3.2.0
  Using premailer 1.21.0
  Using factory_bot 6.2.1
  Using indefinite_article 0.2.5
  Using letter_opener 1.8.1
  Using oauth2 2.0.9
  Using rubocop 1.56.1
  Using rails_best_practices 1.23.2
  Using aws-sdk-kms 1.71.0
  Using http-cookie 1.0.5
  Using rails-html-sanitizer 1.6.0
  Using capybara 3.39.2
  Using debug 1.8.0
  Using activejob 7.0.7.2
  Using activerecord 7.0.7.2
  Using bullet_train-roles 1.3.18
  Using extended_email_reply_parser 0.5.1
  Using sentry-sidekiq 5.10.0
  Using valid_email 0.1.4
  Using omniauth-oauth2 1.7.3
  Using rubocop-performance 1.19.0
  Using standard-custom 1.0.2
  Using aws-sdk-s3 1.134.0
  Using actionview 7.0.7.2
  Using rest-client 2.1.0
  Using microscope 1.1.1
  Using capybara-email 3.0.2
  Using pagy_cursor 0.6.0
  Using standard-performance 1.2.0
  Using omniauth-stripe-connect 2.10.1
  Using actionpack 7.0.7.2
  Using nice_partials 0.9.3
  Using jbuilder 2.11.5
  Using cloudinary 1.27.0
  Using activestorage 7.0.7.2
  Using actionmailer 7.0.7.2
  Using actioncable 7.0.7.2
  Using omniauth-rails_csrf_protection 0.1.2
  Using railties 7.0.7.2
  Using sprockets-rails 3.4.2
  Using standard 1.31.0
  Using premailer-rails 1.12.0
  Using postmark-rails 0.22.1
  Using cable_ready 5.0.1
  Using actionmailbox 7.0.7.2
  Using actiontext 7.0.7.2
  Using responders 3.1.0
  Using doorkeeper 5.6.6
  Using cssbundling-rails 1.2.0
  Using factory_bot_rails 6.2.0
  Using jsbundling-rails 1.1.2
  Using sentry-rails 5.10.0
  Using turbo-rails 1.4.0
  Using web-console 4.2.0
  Using stimulus-rails 1.2.2
  Using devise 4.9.2
  Using rails 7.0.7.2
  Using devise-pwned_password 0.1.10
  Using bullet_train-fields 1.3.18 from source at `local/bullet_train-core/bullet_train-fields`
  Using devise-two-factor 5.0.0
  Using bullet_train-has_uuid 1.3.18 from source at `local/bullet_train-core/bullet_train-has_uuid`
  Using bullet_train-routes 1.0.0
  Using bullet_train-super_load_and_authorize_resource 1.3.18 from source at `local/bullet_train-core/bullet_train-super_load_and_authorize_resource`
  Using bullet_train-themes 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-themes`
  Using showcase-rails 0.4.6
  Using jbuilder-schema 2.2.0
  Using bullet_train-integrations 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-integrations`
  Using bullet_train-integrations-stripe 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-integrations-stripe`
  Using bullet_train-obfuscates_id 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-obfuscates_id`
  Using bullet_train-outgoing_webhooks 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-outgoing_webhooks`
  Using bullet_train-scope_questions 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-scope_questions`
  Using bullet_train-sortable 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-sortable`
  Using magic_test 0.0.9
  Using bullet_train 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train`
  Using bullet_train-api 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-api`
  Using bullet_train-super_scaffolding 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-super_scaffolding`
  Using bullet_train-themes-tailwind_css 1.3.18 from source at `local/bullet_train-core/bullet_train-themes-tailwind_css`
  Using bullet_train-incoming_webhooks 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-incoming_webhooks`
  Using bullet_train-themes-light 1.3.17 (was 1.3.18) from source at `../bullet_train-core/bullet_train-themes-light`
  Bundle complete! 58 Gemfile dependencies, 229 gems now installed.
  Use `bundle info [gemname]` to see where a bundled gem is installed.

> git diff
diff --git a/Gemfile b/Gemfile
index a677d6b9..a6878f22 100644
--- a/Gemfile
+++ b/Gemfile
@@ -97,20 +97,20 @@ end
 # This section is the list of Ruby gems included by default for Bullet Train.
 
 # Core packages.
-gem "bullet_train"
-gem "bullet_train-super_scaffolding"
-gem "bullet_train-api"
-gem "bullet_train-outgoing_webhooks"
-gem "bullet_train-incoming_webhooks"
-gem "bullet_train-themes"
-gem "bullet_train-themes-light"
-gem "bullet_train-integrations"
-gem "bullet_train-integrations-stripe"
+gem "bullet_train", path: "../bullet_train-core/bullet_train"
+gem "bullet_train-super_scaffolding", path: "../bullet_train-core/bullet_train-super_scaffolding"
+gem "bullet_train-api", path: "../bullet_train-core/bullet_train-api"
+gem "bullet_train-outgoing_webhooks", path: "../bullet_train-core/bullet_train-outgoing_webhooks"
+gem "bullet_train-incoming_webhooks", path: "../bullet_train-core/bullet_train-incoming_webhooks"
+gem "bullet_train-themes", path: "../bullet_train-core/bullet_train-themes"
+gem "bullet_train-themes-light", path: "../bullet_train-core/bullet_train-themes-light"
+gem "bullet_train-integrations", path: "../bullet_train-core/bullet_train-integrations"
+gem "bullet_train-integrations-stripe", path: "../bullet_train-core/bullet_train-integrations-stripe"
```
</details>

I think the next step is to write tests for this and ensure everything's working properly. I plan on taking the contents of the Gemfile, placing them in a temp file, then using `bin/link --hack [custom-path]` to manually point to where the gems are using `bundle show`

**Comment by jagthedrummer** [comment]
Weird. I just tried again and it worked as expected. It's very likely something about my setup or repos. I may have been on a weird branch or something. If it happens again I'll try to dig in a little to see what I can figure out. Closing this for now.

**Comment by gazayas** [comment]
No problem!
